### ISSUE TITLE
JobDriver error loop on Downed Refugee Quest

### ISSUE THREAD

**Issue by ArchieBeepBoop** [emipa606/ForgelingsRace#2]
Hey there!

I've been researching an issue that I've been having every time a downed refugee event happens and Forgelings seems to be the issue, as after disabling several mods the crashes stopped and re-appeared once this was back into the load order. I've tested the mod by itself and its requirements and the issue persists, as observed in the modlist below.

To reproduce, force a downed refugee opportunity quest via the dev menu for initiating quests and unpause the game. An infinite loop of JobDriver errors should show up. This behavior is also observed with the downed refugee quest spawning normally. The downed survivor does not have to be necessarily a forgeling.

Modlist: https://rentry.co/enb4y

Log: https://pastebin.com/FJRNp52K (Hugslib was down)

**Comment by emipa606** [comment]
Found the issue, when the original mod was created the author copied the think-tree for humanoids but they also got the thinktree-constant definition in the file. This meant that it was overwritten by the one in the mod for all humanoids.  This was okay for 1.3 where it was copied from but 1.4 changed stuff. Should be fixed in 97312de
